spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: bff-bank
        uri: http://bff-bank:9090
        predicates[0]: Path=/client/**